# Generated by Django 5.0.1 on 2024-01-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=255)),
                ('date', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
                ('precip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='weatherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('mean_max_temp', models.IntegerField()),
                ('mean_min_temp', models.IntegerField()),
                ('total_precip', models.IntegerField()),
            ],
        ),
    ]
